services:
  - type: web
    name: thealankriti-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://thealankriti_db_user:ZwHIC6cxgHdKzy50@thealankriti.b27onwb.mongodb.net/?retryWrites=true&w=majority&appName=thealankriti
      - key: JWT_SECRET
        value: The Alankriti-jewells-super-secret-key-2024
      - key: PORT
        value: "10000"
      - key: ADMIN_EMAIL
        value: bewithu.aj@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: JWT_EXPIRE
        value: 7d

  - type: static
    name: thealankriti-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://thealankriti-backendd.onrender.com/api
